---
title: "armacrypto"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tseries)
library(ggpubr)
library(forecast)
set.seed(2022)
```



```{r}
ggAcf(btc2$diffe,type = "correlation",lag.max = 50)+labs(title = "bitcoin")
ggAcf(ada2$diffe,type = "correlation")+labs(title = "Cardano")
ggAcf(ltc2$diffe,type = "correlation",lag.max = 50)+labs(title = "bitcoin")
ggAcf(eth2$diffe,type = "correlation")+labs(title = "Cardano")

```




```{r}
btc_ar <- arima(btc$Close , order = c(1,1,5)) %>% forecast(h=20) %>% autoplot()

summary(btc_ar)

re<-residuals(btc_ar)


fit <- btc$Close-re

ts.plot(btc$Close)*points(fit, type = "l", col = 2, lty = 2)

```

```{r}

btc2$diffe %>%
Arima(,order=c(1,1,0)) %>%
forecast(h=4) %>%
autoplot


```


```{r}
btcts <- ts(btc$Close,start=c(2014,09,22),end = c(2022,01,04),frequency = 48)
air.model <- Arima(window(btcts,end=2020+11/12),order=c(0,1,1),
                   seasonal=list(order=c(0,1,1),period=12),lambda=0)
plot(forecast(air.model,h=48))
lines(btcts)

# Apply fitted model to later data
air.model2 <- Arima(window(btcts,start=2020+11/12),model=air.model)

# Forecast accuracy measures on the log scale.
# in-sample one-step forecasts.
accuracy(air.model)
# out-of-sample one-step forecasts.
accuracy(air.model2)
# out-of-sample multi-step forecasts
accuracy(forecast(air.model,h=48,lambda=NULL),
         log(window(btcts,start=2021+11/12)))

```






```{r}


acf(btc$Close,lag.max = 1000)
acf(btc2$diffe,lag.max = 1000)
```

