---
title: "stat460"
author: "Henrique Magalhaes Rio"
date: "4/18/2022"
output:
  word_document: default
  html_document: default
---

```{r}
library(OpenImageR)
library(dplyr)
library(ggbiplot)
library(dplyr)
library(MASS)
library(klaR)
library(ggpubr)
library(caret)
library(class)
```



```{r}


path="C:/Users/henri/econ436/Training/glioma_tumor"

setwd(path)
Files <- list.files()
Results <- list()
for(i in seq_along(Files)){
      Image <- readImage(Files[i])
      Resized <- resizeImage(Image, width = 200, height = 200)
      Gray <- rgb_2gray(Resized)
      Results[[i]] <- Gray
}


```


```{r}


path="C:/Users/henri/econ436/Training/no_tumor"

setwd(path)
Files <- list.files()
Results2 <- list()
for(i in seq_along(Files)){
      Image <- readImage(Files[i])
      Resized <- resizeImage(Image, width = 200, height = 200)
      Gray <- rgb_2gray(Resized)
      Results2[[i]] <- Gray
}


```

```{r}


path="C:/Users/henri/econ436/Testing/glioma_tumor"

setwd(path)
Files <- list.files()
Results3 <- list()
for(i in seq_along(Files)){
      Image <- readImage(Files[i])
      Resized <- resizeImage(Image, width = 200, height = 200)
      Gray <- rgb_2gray(Resized)
      Results3[[i]] <- Gray
}


```

```{r}


path="C:/Users/henri/econ436/Testing/no_tumor"

setwd(path)
Files <- list.files()
Results4 <- list()
for(i in seq_along(Files)){
      Image <- readImage(Files[i])
      Resized <- resizeImage(Image, width = 200, height = 200)
      Gray <- rgb_2gray(Resized)
      Results4[[i]] <- Gray
}


```


```{r}
pca<-prcomp(Results[[1]])

compressed.img1 <- pca$x[,50:200] %*% t(pca$rotation[,50:200])
compressed.img2 <- pca$x[,1:50] %*% t(pca$rotation[,1:50])
ggbiplot(pca,var.axes = F)
var_explained = pca$sdev^2 / sum(pca$sdev^2)

ggplot()+geom_line(aes(x=1:10,y=var_explained[1:10]))+scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9,10))+geom_point(aes(x=1:10,y=var_explained[1:10]))+labs(x="Principal Component",y="Percentage of Variance Explained",title = "Scree Plot")


```


```{r}
pca<-prcomp(Results2[[200]])

compressed.img3 <- pca$x[,1:50] %*% t(pca$rotation[,1:50])
compressed.img4 <- pca$x[,50:200] %*% t(pca$rotation[,50:200])
 

```



```{r}
df <- data.frame(matrix(ncol = 200, nrow = 826))

for(i in 1:826){

pca<-prcomp(Results[[i]])
row <-pca$x[,1]

df[i,]<-row


}

```







```{r}
df2 <- data.frame(matrix(ncol = 200, nrow = 395))

for(i in 1:395){

pca<-prcomp(Results2[[i]])

row <-pca$x[,1]

df2[i,]<-row


}

```



```{r}
df3 <- data.frame(matrix(ncol = 200, nrow =100))

for(i in 1:100){

pca<-prcomp(Results3[[i]])

row <-pca$x[,1]

df3[i,]<-row


}

```






```{r}
df4 <- data.frame(matrix(ncol = 200, nrow =100))

for(i in 1:100){

pca<-prcomp(Results4[[i]])

row <-pca$x[,1]

df4[i,]<-row


}

```



```{r}

df<-df %>%
  mutate(cancer="Tumor")

df2 <-df2 %>% mutate(cancer="No Tumor")

data <-rbind(df,df2)


pca2 <- prcomp(data[,1:200],scale. = TRUE)




```


```{r}

df3<-df3 %>%
  mutate(cancer="Tumor")

df4 <-df4 %>% mutate(cancer="No Tumor")

testing <-rbind(df3,df4)


pca3 <- prcomp(testing[,1:200],scale. = TRUE)




```



```{r}
ggbiplot(pca2,groups = as.factor(data$cancer),var.axes = F)
```

```{r}
ggbiplot(pca3,groups = as.factor(testing$cancer),var.axes = F)
```

 



```{r}
clust <- hclust(dist(data[,1:2]))

plot(clust)
```




```{r}
cutree <- cutree(clust,k=2)

table(cutree)

```



```{r}
lda <-partimat(as.factor(cancer) ~ X2+X1, data = data,method="lda")


```


```{r}
logi <- glm(as.factor(cancer)~.,data=data,family="binomial")

prob <- predict(logi, testing, type = "response")

pred <- ifelse(prob>0.5, "Tumor", "No Tumor")



confusionMatrix(as.factor(pred),as.factor(testing$cancer))
```





```{r}

lda2 <- lda(as.factor(cancer)~.,data=data)

predlda <- predict(lda2,newdata=testing)


confusionMatrix(as.factor(predlda$class),as.factor(testing$cancer))
```

```{r}
knnModel <- train(as.factor(cancer) ~., 
                  data = data, 
                  method = 'knn')


```




```{r}
knn <-knn(train=data[,1:200],test=testing[,1:200],cl=data$cancer,k=1)

confusionMatrix(as.factor(knn),as.factor(testing$cancer))
```






