---
title: "VARS"
author: "Henrique Magalhaes Rio"
date: "3/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tseries)
library(ggpubr)
library(forecast)
library(lubridate)
library(lmtest)
library(vars)
set.seed(2022)
data <- read.csv("CLOSINGPRICEDATA.csv")

```




```{r,echo=FALSE}


#data$Date <-mdy(data$Date)


datadif <-data  %>% mutate(difbtc = log(data$BTC) - log(lag(data$BTC)))

datadif <-datadif %>% mutate(difada = log(data$ADA) - log(lag(data$ADA)))

datadif <-datadif  %>% mutate(difwave = log(data$WAVES) - log(lag(data$WAVES)))

datadif <-datadif  %>% mutate(difeth = log(data$ETH) - log(lag(data$ETH)))

datadif$Date <- as.Date(data$Date)
data1 <- datadif[2:100,8:11]
data2 <- datadif[100:210,8:11]


```

# Lag Selection 


```{r}
lagselect <- VARselect(data1,lag.max =16)

lagselect$selection
```



# Bitcoin

```{r}
var1 <- VAR(data1,p=15,type = 'const')

```


# Period 1 

```{r warning=FALSE}
pred <- predict(var1,ahead=10)

fore <- pred$fcst
mse <- mean(residuals(var1)[,1]^2)

rmse <- sqrt(mse)
ggplot()+geom_line(aes(x=as.Date(Date),y=difbtc),data = datadif[2:110,])+
  scale_x_date(date_labels = "%m-%Y",breaks = scales::pretty_breaks(n = 15))+geom_line(aes(x=as.Date(data[101:110,]$Date),y=fore$difbtc[,1]),color='red')+labs(title="VAR forecasts for Bitcoin Period 1",x="Date")
```

```{r}
ggAcf(resid(var1))
fanchart(pred)

```



# ADA

```{r warning=FALSE}
pred <- predict(var1,ahead=10)

fore <- pred$fcst

ggplot()+geom_line(aes(x=as.Date(Date),y=difada),data = datadif[2:110,])+
  scale_x_date(date_labels = "%m-%Y",breaks = scales::pretty_breaks(n = 15))+geom_line(aes(x=as.Date(data[101:110,]$Date),y=fore$difada[,1]),color='red')+labs(title="VAR forecasts for ADA",x="Date")
```

```{r}
res<-resid(var1)
ggAcf(res[,2])
fanchart(pred)

```










# WAVE


```{r warning=FALSE}
pred <- predict(var1,ahead=10)

fore <- pred$fcst

ggplot()+geom_line(aes(x=as.Date(Date),y=difwave),data = datadif[2:110,])+
  scale_x_date(date_labels = "%m-%Y",breaks = scales::pretty_breaks(n = 15))+geom_line(aes(x=as.Date(data[101:110,]$Date),y=fore$difwave[,1]),color='red')+labs(title="VAR forecasts for ADA",x="Date")
```

```{r}
res<-resid(var1)
ggAcf(res[,3])
fanchart(pred)

```


```{r}
res <- resid(var1)


```




#ETH

```{r warning=FALSE}
pred <- predict(var1,ahead=10)

fore <- pred$fcst

ggplot()+geom_line(aes(x=as.Date(Date),y=difeth),data = datadif[2:110,])+
  scale_x_date(date_labels = "%m-%Y",breaks = scales::pretty_breaks(n = 15))+geom_line(aes(x=as.Date(data[101:110,]$Date),y=fore$difeth[,1]),color='red')+labs(title="VAR forecasts for ADA",x="Date")
```

```{r}
res<-resid(var1)
ggAcf(res[,4])
fanchart(pred)

```


```{r}
res <- resid(var1)


```





